fix: fix integration with Spring Boot 3
The library creates the following queries:

- 1 count query (unfiltered, to compute the "recordsTotal" field)
- 1 data query (filtered)
- 1 optional count query (filtered), if the data query returns a complete slice, in order to compute the "recordsFiltered" field

Before this commit, when the optional count query ran,
DataTablesSpecification.toPredicate() was called a second time and
reused the globalPredicates array, triggering one of the following
error:

> java.lang.IllegalArgumentException: Already registered a copy

> jakarta.persistence.PersistenceException: Converting org.hibernate.sql.ast.SqlTreeCreationException to JPA PersistenceException : Could not locate TableGroup

Related: https://github.com/darrachequesne/spring-data-jpa-datatables/issues/150